#' @title Reshape from wide to long format.
#' @description To convert data generated by the function gen_datatraj into a long format.
#' @name widetolong
#' @param obsdata the data to reshape in a long format.
#' @param varying varying columns.
#' @return \item{widetolong_dat}{Long format data.}
#' @examples
#' longdata = widetolong(obsdata = gendatatraj(), varying = 1:5)
#' head(longdata)
#' @export widetolong
#' @author Awa Diop, Denis Talbot

widetolong <- function(obsdata, varying){
args <- match.call()

#Input check
if(!("obsdata" %in% names(args))) stop("Obsdata is missing, with no default")
if(!("varying" %in% names(args))) stop("Varying columns not specified")

widetolong_dat <- reshape(obsdata, direction = "long", varying = varying, sep = "")
  return(widetolong_dat)

}
